### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#359]
There is a bug where some browsers are not able to load the login page (It might be all pages but I can only tell that the login page does not load at this point). They are just presented with a blue background and nothing happens.

It has been very difficult to track down because I could not reproduce it even with cross platform testing but I have been able to reproduce the error on my phone (iOS) and subsequently by setting the mobile responsiveness setting in chrome.

![screen shot 2016-07-12 at 09 12 31](https://cloud.githubusercontent.com/assets/7042623/16758295/05107d90-4811-11e6-9296-e75f3e1b2481.png)

I can confirm that the error message is the same for a large number of windows users on both chrome and edge:

```
vendor-c6ae6fe98d.js:137493 Uncaught TypeError: Cannot read property 'mouse' of undefined(anonymous function) @ vendor-c6ae6fe98d.js:137493(anonymous function) @ vendor-c6ae6fe98d.js:137628
app-0eb4464514.js:23680 Uncaught ReferenceError: toastr is not defined(anonymous function) @ app-0eb4464514.js:23680(anonymous function) @ app-0eb4464514.js:23693
vendor-c6ae6fe98d.js:9279 Uncaught Error: [$injector:modulerr] Failed to instantiate module halo due to:
Error: [$injector:modulerr] Failed to instantiate module infinite-scroll due to:
Error: [$injector:nomod] Module 'infinite-scroll' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.5/$injector/nomod?p0=infinite-scroll
    at http://54.204.233.217/scripts/vendor-c6ae6fe98d.js:42:376
    at http://54.204.233.217/scripts/vendor-c6ae6fe98d.js:42:10697
    at n (http://54.204.233.217/scripts/vendor-c6ae6fe98d.js:42:10170)
    at http://54.204.233.217/scripts/vendor-c6ae6fe98d.js:42:10482
    at http://54.204.233.217/scripts/vendor-c6ae6fe98d.js:42:19607
    at i (http://54.204.233.217/scripts/vendor-c6ae6fe98d.js:42:824)
    at h (http://54.204.233.217/scripts/vendor-c6ae6fe98d.js:42:19455)
    at http://54.204.233.217/scripts/vendor-c6ae6fe98d.js:42:19624
    at i (http://54.204.233.217/scripts/vendor-c6ae6fe98d.js:42:824)
    at h (http://54.204.233.217/scripts/vendor-c6ae6fe98d.js:42:19455)
http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=infinite-scroll&p1=…(http%3A%2F%2F54.204.233.217%2Fscripts%2Fvendor-c6ae6fe98d.js%3A42%3A19455)
    at http://54.204.233.217/scripts/vendor-c6ae6fe98d.js:42:376
    at http://54.204.233.217/scripts/vendor-c6ae6fe98d.js:42:19883
    at i (http://54.204.233.217/scripts/vendor-c6ae6fe98d.js:42:824)
    at h (http://54.204.233.217/scripts/vendor-c6ae6fe98d.js:42:19455)
    at http://54.204.233.217/scripts/vendor-c6ae6fe98d.js:42:19624
    at i (http://54.204.233.217/scripts/vendor-c6ae6fe98d.js:42:824)
    at h (http://54.204.233.217/scripts/vendor-c6ae6fe98d.js:42:19455)
    at nt (http://54.204.233.217/scripts/vendor-c6ae6fe98d.js:42:21410)
    at a (http://54.204.233.217/scripts/vendor-c6ae6fe98d.js:42:8240)
    at oe (http://54.204.233.217/scripts/vendor-c6ae6fe98d.js:42:8550)
http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=halo&p1=Error%3A%20…0(http%3A%2F%2F54.204.233.217%2Fscripts%2Fvendor-c6ae6fe98d.js%3A42%3A8550)
```

**Comment by tarkal** [comment]
Latest commit has fixed this issue on client system. I can also confirm it works on iOS and simulated in chrome.
